version: '3.4'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=identity-project
    volumes:
      - db-data:/var/lib/mysql/
    ports:
      - "3306:3306"
volumes:
  db-data: {}
