version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Anime404
    ports:
      - 27017:27017
    volumes:
      - data.data


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSER: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Anime404
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  data: {}